"""guest_credits

Revision ID: 170c780f18d6
Revises: 1551d5331491
Create Date: 2026-06-21 13:07:03.006224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '170c780f18d6'
down_revision: Union[str, Sequence[str], None] = '1551d5331491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_credits',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_credits_guest_id'), 'guest_credits', ['guest_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guest_credits_guest_id'), table_name='guest_credits')
    op.drop_table('guest_credits')
    # ### end Alembic commands ###
